apiVersion: apps/v1
kind: Deployment
metadata:
  name: murmuration-ui
  namespace: murmuration-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: murmuration-ui
  template:
    metadata:
      labels:
        app: murmuration-ui
    spec:
      containers:
        - name: ui
          image: {{ .Values.ui.image }}
          imagePullPolicy: {{ .Values.ui.imagePullPolicy }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: murmuration-ui
  namespace: murmuration-system
spec:
  selector:
    app: murmuration-ui
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
